# Generated by Django 5.2.1 on 2025-05-22 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etnomusicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_trabajador', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('fundado_en', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('duracion_dias', models.PositiveIntegerField()),
                ('etnomusicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='Gestion.etnomusicologo')),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='Gestion.museo')),
            ],
        ),
    ]
